### ISSUE TITLE
Abstracting S3

### ISSUE THREAD

**Issue by joeblew99** [spf13/afero#73] opened 2016-02-24 12:51 UTC
It would be useful to abstract s3 http like file systems too.

I have been using Mino. It's really cool because it has 3 different avatar tions itself:
Amazon S3, Google Storage, and its own Minio server.

The minio server is cool because it does dedup and some other smarts too.

So,my suggestion is to incorporate this, so it works with the existing API.

What do others think ?

**Comment by joeblew99** [comment] 2016-02-24 12:59
Here it is
https://github.com/minio

The golang api is :
https://github.com/minio/minio-go

Their own server ( that can replace S3 or GS) is:
https://github.com/minio/minio

**Comment by mbertschler** [comment] 2016-03-16 11:57
If someone wants to implement this, they should also look into the discussion at #11.

**Comment by kargakis** [comment] 2020-03-27 21:47
Duplicate of https://github.com/spf13/afero/issues/11

**Closed by kargakis** 2020-03-27 21:47 UTC
Labels: enhancement
