### ISSUE TITLE
"go test -v ./..." fails on Windows

### ISSUE THREAD

**Issue by anthonyfok** [spf13/afero#26] opened 2015-12-04 13:17 UTC
While investigating https://github.com/spf13/hugo/pull/1669#issuecomment-161932753, I first tried using `Readdirnames(0)` in `hugo/commands/new_test.go` to see what actually got created, and after seeing it returns `[content]` on Linux, but returns `[C:\Users\Veronica\AppData\Local\Temp\blog\content]` on Windows, I tried to use `afero.Walk()` to see what files/directories actually gets created in TestDoNewSite_error_force_dir_inside_exists(), I ran into a runtime error of "invalid memory address or nil pointer deferenced" on Windows 8.1 (amd64) running go1.5.1.

I then decided to try `go test -v ./...` on afero itself, and got the following results:

```
=== RUN   TestRead0
--- PASS: TestRead0 (0.00s)
=== RUN   TestOpenFile
--- PASS: TestOpenFile (0.00s)
=== RUN   TestMemFileRead
--- PASS: TestMemFileRead (0.00s)
=== RUN   TestRename
--- FAIL: TestRename (0.00s)
	fs_test.go:160: File was not renamed to renameto
=== RUN   TestRemove
--- FAIL: TestRemove (0.00s)
	fs_test.go:178: OsFs: Remove() failed: remove /tmp/afero/test.txt: The process cannot access the file because it is being used by another process.
=== RUN   TestTruncate
--- PASS: TestTruncate (0.00s)
=== RUN   TestSeek
--- PASS: TestSeek (0.00s)
=== RUN   TestReadAt
--- PASS: TestReadAt (0.00s)
=== RUN   TestWriteAt
--- PASS: TestWriteAt (0.00s)
=== RUN   TestReaddirnames
--- FAIL: TestReaddirnames (0.00s)
	fs_test.go:325: remove /tmp/afero\test.txt: The process cannot access the file because it is being used by another process.
=== RUN   TestReaddirSimple
--- FAIL: TestReaddirSimple (0.00s)
	fs_test.go:389: file does not exist
=== RUN   TestReaddir
--- FAIL: TestReaddir (0.00s)
	fs_test.go:421: open /tmp/afero/we/have/to/go/deeper: The system cannot find the path specified.
=== RUN   TestWalk
--- FAIL: TestWalk (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x49c8ea]

goroutine 17 [running]:
testing.tRunner.func1(0xc082060a20)
	c:/go/src/testing/testing.go:450 +0x178
github.com/spf13/afero.TestWalk.func1(0x78f440, 0xa, 0x0, 0x0, 0x2130028, 0xc0820021d0, 0x0, 0x0)
	C:/Users/Veronica/GoPath/src/github.com/spf13/afero/fs_test.go:466 +0x6a
github.com/spf13/afero.Walk(0x78f440, 0xa, 0xc082037f18, 0x2134790, 0xc082002e30, 0x0, 0x0)
	C:/Users/Veronica/GoPath/src/github.com/spf13/afero/fs.go:200 +0xc9
github.com/spf13/afero.TestWalk(0xc082060a20)
	C:/Users/Veronica/GoPath/src/github.com/spf13/afero/fs_test.go:472 +0x1c9
testing.tRunner(0xc082060a20, 0x92a840)
	c:/go/src/testing/testing.go:456 +0x9f
created by testing.RunTests
	c:/go/src/testing/testing.go:561 +0x874

goroutine 1 [chan receive]:
testing.RunTests(0x81c158, 0x92a720, 0xf, 0xf, 0x2134800)
	c:/go/src/testing/testing.go:562 +0x8b4
testing.(*M).Run(0xc08206ded8, 0x0)
	c:/go/src/testing/testing.go:494 +0x77
main.main()
	github.com/spf13/afero/_test/_testmain.go:82 +0x11d
exit status 2
FAIL	github.com/spf13/afero	0.321s
```

**Comment by anthonyfok** [comment] 2015-12-04 13:31
> I first tried using `Readdirnames(0)` in hugo/commands/new_test.go to see what actually got created, and after seeing it returns `[content]` on Linux, but returns `[C:\Users\Veronica\AppData\Local\Temp\blog\content]` on Windows...

Sorry, this info I provided is incomplete and inaccurate.  The actual code I used inside TestDoNewSite_error_force_dir_inside_exists() was:

```go
        f, err := hugofs.SourceFs.Open(basepath)
        fmt.Println(f.Readdirnames(0))
```

which, when compiled with afero HEAD at 55789de (with the new normalizePath()), returns:

```
[] <nil>
```

but shows something when compiled with afero at commit 75dc847 (with normalizePath() removed):

```
[C:\Users\Veronica\AppData\Local\Temp\blog\content] <nil>
```

**Comment by spf13** [comment] 2015-12-09 03:02
I just resolved the bug that was affecting the Hugo tests (and execution) on Windows. My suspicion about these errors is that the tests themselves need to be rewritten because they were written in an OS specific manner.

**Comment by moorereason** [comment] 2015-12-09 06:12
I looked at this for a while this evening.  The root cause of most of the issues is the use of `path.Split` instead of `filepath.Split` in memfile.go ([L115](https://github.com/spf13/afero/blob/daf7a87d8f9aca2b7c6effb9cc083a9a9ff9f115/memfile.go#L115) and [L216](https://github.com/spf13/afero/blob/daf7a87d8f9aca2b7c6effb9cc083a9a9ff9f115/memfile.go#L216)), and a hard-coded path separator in memmap.go ([L216](https://github.com/spf13/afero/blob/daf7a87d8f9aca2b7c6effb9cc083a9a9ff9f115/memmap.go#L216)).  I think these are actual bugs.

Then there's just a bazillion ways that the tests need to be updated to not assume a unix path separator.  It's also a little confusing that so many of the error messages don't include `fs.Name()` in the output.

**Comment by spf13** [comment] 2015-12-09 21:12
closed by https://github.com/spf13/afero/commit/943d877c43bb849079aed87319d0c4073f2d8609

**Closed** 2015-12-09 21:12 UTC
