### ISSUE TITLE
MemMapFs.Create() works without parent directory

### ISSUE THREAD

**Issue by sqwishy** [spf13/afero#168] opened 2018-05-25 16:03 UTC
MemMapFs's create doesn't seem to care about missing parent directories.
```
func TestMemFsCreate(t *testing.T) {
	fs := NewMemMapFs()
	if _, err := fs.Create("/tmp/t/not-a-real-directory/bar"); err == nil {
		t.Error("wow")
	}
}
```
This test fails, because `fs.Create()` does not return an error. If you use `os.Create()`, an error is returned and the test passes.

**Comment by sqwishy** [comment] 2018-05-25 16:42
The above was a discrepancy that I discovered while trying to explain another issue I was having, which is reproducible below.

In this case, Walk will see "tmp" twice. It must have something to do with the MkdirAll and Create going through different Fs objects, since the weirdness goes away if they both use either the `MemMapFs` or `BasePathFs`. Maybe this isn't supported? I'm not really sure, what's going on here.
```
func TestMemFsCreate(t *testing.T) {
	where := "tmp/hi"
	fs := NewMemMapFs()
	fs.MkdirAll(path.Dir(where), os.ModePerm)
	fs2 := NewBasePathFs(fs, "/")
	if _, err := fs2.Create(where); err == nil {
		t.Error("wow")
	}
	Walk(fs, "", func(path string, info os.FileInfo, err error) error {
		fmt.Println(path, info)
		return nil
	})
}
```

**Comment by kargakis** [comment] 2020-03-27 21:43
Duplicate of https://github.com/spf13/afero/issues/149

**Closed by kargakis** 2020-03-27 21:43 UTC
Labels: bug
