### ISSUE TITLE
1.1.2 has mailformed go.mod

### ISSUE THREAD

**Issue by rslarson** [spf13/afero#277] opened 2020-11-28 19:41 UTC
When running `$ go mod tidy` I am getting the below error:

```
$ go mod tidy
go: finding module for package github.com/mitchellh/go-homedir
go: finding module for package github.com/spf13/viper
go: finding module for package github.com/spf13/cobra
go: found github.com/mitchellh/go-homedir in github.com/mitchellh/go-homedir v1.1.0
go: found github.com/spf13/cobra in github.com/spf13/cobra v1.1.1
go: found github.com/spf13/viper in github.com/spf13/viper v1.7.1
go: github.com/spf13/viper@v1.7.1 requires
        github.com/spf13/afero@v1.1.2/go.mod: verifying module: github.com/spf13/afero@v1.1.2/go.mod: malformed record data
```

Looking at the go.mod in the 1.1.2 release, I think the go version is missing, so hopefully this is an easy fix.  I would submit a PR but I do not feel familiar enough with the underlying code to suggest an appropriate fix.

My current go.mod file:
```
module github.com/rslarson/speedtracker

go 1.14

require (
	github.com/golang/protobuf v1.4.3
	google.golang.org/grpc v1.33.2
	google.golang.org/protobuf v1.25.0
)
```

**Comment by kargakis** [comment] 2020-11-29 19:52
I cannot reproduce this in [master](https://github.com/spf13/afero/commit/736b98e92cbd0898a0aebdc9ecd04dbde32f8c68) so I am going to close this issue.

**Closed by kargakis** 2020-11-29 19:52 UTC
